version: ~> 1.0
language: python

branches:
  only:
    - master

before_install:
  - export CONDA_PY="3.7"
  - export DIR=`pwd`
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/ci/miniconda_install.sh
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
  - . miniconda_install.sh

install:
  - conda install -y -c conda-forge pyyaml pytest pytest-cov nbval
  - conda install -y -c conda-forge sqlalchemy  # one extra install here
  - pushd ..
  - . ${DIR}/conda_ops_dev_install.sh dwhswenson
  - pushd openpathsampling && git fetch && popd
  - popd
  - pip install codecov

script:
  - cd ../openpathsampling && git checkout origin/storage && cd -
  - OPS_GIT=`python -c "import openpathsampling; print(openpathsampling.version.git_hash)"`
  - cd ../openpathsampling && ROOT=`pwd` && cd -
  - ./test-storage.sh
  - codecov -t $CODECOV_TOKEN --root $ROOT -c $OPS_GIT -b storage -f unit.xml -F storage-unit
  - codecov -t $CODECOV_TOKEN --root $ROOT -c $OPS_GIT -b storage -f integration.xml -F storage-integration
  - ./test-examples.sh
  - cd ../openpathsampling && git checkout origin/storable_functions && cd -
