version: ~> 1.0
language: python

branches:
  only:
    - master

before_install:
  - export CONDA_PY="37"
  - export DIR=`pwd`
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/ci/miniconda_install.sh
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
  - . miniconda_install.sh

install:
  - conda install -y -c conda-forge pyyaml pytest pytest-cov nbval
  - pushd ..
  - . ${DIR}/conda_ops_dev_install.sh dwhswenson
  - pushd openpathsampling && git fetch && popd
  - popd

script:
  - cd ../openpathsampling && git checkout origin/storage && cd -
  - ./test-schema.sh
  - cd ../openpathsampling && git checkout origin/storable_functions && cd -
