version: ~> 1.0
language: python

branches:
  only:
    - master

before_install:
  - export CONDA_PY="37"
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/ci/miniconda_install.sh
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
  - bash miniconda_install.sh
  - conda install -y -c conda-forge pytest pytest-cov nbval

install:
  - bash conda_ops_dev_install.sh dwhswenson
  - cd openpathsampling && git fetch && cd -

script:
  - cd openpathsampling && git checkout origin/storage && cd -
  - ./test-schema.sh
  - cd openpathsampling && git checkout origin/storable_functions && cd -
