name: "Tests"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  schedule:
    - cron: "0 4 * * *"

defaults:
  run:
    shell: bash -l {0}

jobs:
  ops-master:
    runs-on: ubuntu-latest
    name: "OPS Master"
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: "Installation"
        run: |
          curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
          DIR=`pwd`
          conda install -y -c conda-forge pyyaml pytest pytest-cov nbval pip
          conda install -y -c conda-forge sqlalchemy
          python -m pip install codecov
          pushd ..
          CONDA_PY="3.7" source ${DIR}/conda_ops_dev_install.sh
          popd
      - name: "Fixes"
        run: |
          # for some reason, conda is currently pulling in (old) networkx 2.3 and
          # matplotlib 3.4.1 (which is new, but not compatible)
          conda update -y -c conda-forge networkx
          # it looks like we're getting errors on old pyparsing (before 3.0)
          conda update -y -c conda-forge pyparsing>=3.0.4
      - name: "Versions"
        run: conda list
      - name: "Tests"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cd ../openpathsampling && ROOT=`pwd` && cd -
          OPS_GIT=`python -c "import openpathsampling; print(openpathsampling.version.git_hash)"`
          . ./test-storage.sh
          codecov -t $CODECOV_TOKEN --root $ROOT -c $OPS_GIT -b master -f unit.xml -F storage-unit
          codecov -t $CODECOV_TOKEN --root $ROOT -c $OPS_GIT -b master -f integration.xml -F storage-integration
          . ./test-examples.sh


