name: "Tests"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  schedule:
    - cron: "0 4 * * *"

defaults:
  run:
    shell: bash

jobs:
  ops-master:
    runs-on: ubuntu-latest
    name: "OPS Master"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: "Installation"
        run: |
          curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
          conda install -y -c conda-forge pyyaml pytest pytest-cov nbval pip
          conda install -y -c conda-forge sqlalchemy
          pip install codecov
          . ./conda_ops_dev_install.sh
      - name: "Tests"
        run: |
          cd openpathsampling && ROOT=`pwd` && cd -
          OPS_GIT=`python -c "import openpathsampling; print(openpathsampling.version.git_hash)"`
          . ./test-storage.sh
          codecov -t $CODECOV_TOKEN --root $ROOT -c $OPS_GIT -b master -f unit.xml -F storage-unit
          codecov -t $CODECOV_TOKEN --root $ROOT -c $OPS_GIT -b master -f integration.xml -F storage-integration
          . ./test-examples.sh


